pub(crate) mod test_stdin;
pub(crate) mod test_args;
pub(crate) mod test_vars;
pub(crate) mod test_var_logging;
pub(crate) mod creating_files;
pub(crate) mod using_open_options;
pub(crate) mod test_blocking_get;
pub(crate) mod test_reqwest_with_tokio;
pub(crate) mod async_without_join_macro;
mod async_with_join;
